### ISSUE TITLE
Re-ID model

### ISSUE THREAD

**Issue by paleomoon** [viplix3/BoTSORT-cpp#1]
Hi! I added Re-ID model, but get some Eigen Assertion error, do you have any update?

**Comment by viplix3** [comment]
@paleomoon sorry but some other projects have been keeping me busy, would it possible for you to raise a PR?

I could take a look at it over the weekend.

**Comment by paleomoon** [comment]
@viplix3 thank you for your quick reply, I'm running Re-ID model on some special hardware paltform, not NVIDIA, I will try to migrate to NVIDIA and make a PR.

**Comment by viplix3** [comment]
Hi @paleomoon, let me know if you were able to find some time for this.
If not, I'll start working on adding a TensorRT implementation for Re-ID models.

**Comment by paleomoon** [comment]
Hi, @viplix3, sorry I have been busy these days, you can start working on it, just pay attention to the last few lines of [this](https://github.com/viplix3/BoTSORT-cpp/blob/main/botsort/src/KalmanFilter.cpp), I changed to [this](https://github.com/shaoshengsong/DeepSORT/blob/master/tracker/deepsort/src/kalmanfilter.cpp), error disappeared.
