### ISSUE TITLE
error！！！

### ISSUE THREAD

**Issue by huangzongmou** [viplix3/BoTSORT-cpp#3]
error: too many arguments to function ‘double cv::findTransformECC(cv::InputArray, cv::InputArray, cv::InputOutputArray, int, cv::TermCriteria, cv::InputArray)’
         cv::findTransformECC(_prev_frame, frame, H_cvMat, cv::MOTION_EUCLIDEAN, _termination_criteria, cv::noArray(), 1);

**Comment by viplix3** [comment]
@huangzongmou I believe this is caused due to changes in OpenCV api between OpenCV 3.xx and 4.xx.
Could you please let me know the OpenCV version installed on your system?

In the mean time I’ll try and update the code to take this into account.

**Comment by huangzongmou** [comment]
您好！您的邮件已收到，尽快给你回复。谢谢                                                      黄总谋！

**Comment by huangzongmou** [comment]
"After changing the OpenCV version to 4.5.5, the issue has been resolved. Thank you."

**Comment by huangzongmou** [comment]
> 



> @huangzongmou I believe this is caused due to changes in OpenCV api between OpenCV 3.xx and 4.xx. Could you please let me know the OpenCV version installed on your system?
> 
> In the mean time I’ll try and update the code to take this into account.

"After changing the OpenCV version to 4.5.5, the issue has been resolved. Thank you."

**Comment by viplix3** [comment]
Thanks for the update @huangzongmou
I'll update the code to have only the relevant functions active as per the available OpenCV version installation.
