### ISSUE TITLE
Add Reid model is no effect?

### ISSUE THREAD

**Issue by ztrong-forever** [viplix3/BoTSORT-cpp#4]
I feel the botsort no effect when i add Reid model or not add Reid model.
I modified Reid on bytetrack, according to your code.

**Comment by viplix3** [comment]
@ztrong-forever I apologize for the delay in my response.

Pairing the tracker with a Re-Identification (Re-ID) model could indeed make a notable difference, particularly in scenarios where ID switches are triggered by long-term associations.

Currently, my schedule is quite tight, which limits my ability to integrate a Re-ID model and fine-tune the algorithm further. However, I am very open to contributions and would be delighted to assist you if you are interested in raising a Pull Request (PR) with this feature. Your initiative could significantly enhance the performance and robustness of the tracking algorithm, and I look forward to potentially collaborating on this improvement.
