### ISSUE TITLE
Warning: Could not estimate affine matrix

### ISSUE THREAD

**Issue by starsky68** [viplix3/BoTSORT-cpp#9]
Warning: Could not estimate affine matrix
May I ask what caused this error and what happened during runtime,

**Comment by viplix3** [comment]
HI @starsky68, there is a camera motion compensation algorithm being used in the project.
When the algorithm is not able to detect any feature points (on the basis of which camera motion is estimated), it throws out this error.

If your use-case doesn't have to deal with camera motion you can comment lines #90 to #92 [here](https://github.com/viplix3/BoTSORT-cpp/blob/42116ceca325b44ba856d40e647f1e41470ab523/botsort/src/BoTSORT.cpp#L90C22-L90C22)
